In [1]:
import torch
from torch import Tensor

In [10]:
data: Tensor = torch.rand(5, 1, 1)
print(data.shape, data)
for d in data:
    print(d.shape, d, d.squeeze().item())

torch.Size([5, 1, 1]) tensor([[[0.7378]],

        [[0.1149]],

        [[0.6903]],

        [[0.3882]],

        [[0.7372]]])
torch.Size([1, 1]) tensor([[0.7378]]) 0.7377938628196716
torch.Size([1, 1]) tensor([[0.1149]]) 0.11485201120376587
torch.Size([1, 1]) tensor([[0.6903]]) 0.6903244256973267
torch.Size([1, 1]) tensor([[0.3882]]) 0.38823235034942627
torch.Size([1, 1]) tensor([[0.7372]]) 0.737197995185852


In [23]:
import torch
import torch.nn as nn

f = nn.BCELoss()
v = .5
t = torch.FloatTensor([
    [0, 0, 0],
    [0, 0, v],
    [0, v, 0],
    [0, v, v],

    [v, 0, 0],
    [v, 0, v],
    [v, v, 0],
    [v, v, v],
])
y = torch.FloatTensor([0, 0, .1])

m = 0
for i, x in enumerate(t):
    z = f(x, y)
    m = min(m, z) if m else z
    print(i, x, y, z, m)

0 tensor([0., 0., 0.]) tensor([0.0000, 0.0000, 0.1000]) tensor(3.3333) tensor(3.3333)
1 tensor([0.0000, 0.0000, 0.5000]) tensor([0.0000, 0.0000, 0.1000]) tensor(0.2310) tensor(0.2310)
2 tensor([0.0000, 0.5000, 0.0000]) tensor([0.0000, 0.0000, 0.1000]) tensor(3.5644) tensor(0.2310)
3 tensor([0.0000, 0.5000, 0.5000]) tensor([0.0000, 0.0000, 0.1000]) tensor(0.4621) tensor(0.2310)
4 tensor([0.5000, 0.0000, 0.0000]) tensor([0.0000, 0.0000, 0.1000]) tensor(3.5644) tensor(0.2310)
5 tensor([0.5000, 0.0000, 0.5000]) tensor([0.0000, 0.0000, 0.1000]) tensor(0.4621) tensor(0.2310)
6 tensor([0.5000, 0.5000, 0.0000]) tensor([0.0000, 0.0000, 0.1000]) tensor(3.7954) tensor(0.2310)
7 tensor([0.5000, 0.5000, 0.5000]) tensor([0.0000, 0.0000, 0.1000]) tensor(0.6931) tensor(0.2310)


In [71]:
import numpy as np
import matplotlib.pyplot as plt

for i in range(3):
    data = np.random.randint(100, 200, 10)
    grad = np.array([(data[i + 1] - data[i]) / data[i] for i in range(len(data) - 1)]).round(2)
    print(grad)
    print(grad + 1)
    print((grad + 1) / 2)
    print('-' * 40)

[ 0.39 -0.43 -0.09  0.61  0.   -0.12  0.05 -0.09  0.04]
[1.39 0.57 0.91 1.61 1.   0.88 1.05 0.91 1.04]
[0.695 0.285 0.455 0.805 0.5   0.44  0.525 0.455 0.52 ]
----------------------------------------
[ 0.57 -0.22 -0.09  0.23  0.18 -0.23  0.26 -0.48  0.2 ]
[1.57 0.78 0.91 1.23 1.18 0.77 1.26 0.52 1.2 ]
[0.785 0.39  0.455 0.615 0.59  0.385 0.63  0.26  0.6  ]
----------------------------------------
[-0.1   0.15 -0.34  0.83 -0.32  0.16  0.23 -0.38  0.67]
[0.9  1.15 0.66 1.83 0.68 1.16 1.23 0.62 1.67]
[0.45  0.575 0.33  0.915 0.34  0.58  0.615 0.31  0.835]
----------------------------------------


In [84]:
import numpy as np

midrange = 0.1  # 표준 편차로 부터
data = np.random.randint(100, 1000, 10)
for i in range(len(data) - 1):
    r = (data[i + 1] - data[i]) / data[i]
    d = 2
    if abs(r) <= midrange:
        d = 1
    elif r < 0:
        d = 0
    print(data[i], data[i + 1], r, d, np.eye(3)[d])

323 720 1.2291021671826625 2 [0. 0. 1.]
720 582 -0.19166666666666668 0 [1. 0. 0.]
582 310 -0.46735395189003437 0 [1. 0. 0.]
310 315 0.016129032258064516 1 [0. 1. 0.]
315 611 0.9396825396825397 2 [0. 0. 1.]
611 619 0.01309328968903437 1 [0. 1. 0.]
619 100 -0.8384491114701131 0 [1. 0. 0.]
100 236 1.36 2 [0. 0. 1.]
236 988 3.1864406779661016 2 [0. 0. 1.]


In [85]:
print(range(0.1, 0.5, 0.1))

TypeError: 'float' object cannot be interpreted as an integer