In [108]:
import torch
import torch.nn as nn

In [109]:
loss = nn.CrossEntropyLoss()

In [110]:
input = torch.randn(1, 3, requires_grad=True)
input

tensor([[ 0.4618, -1.0391,  0.1742]], requires_grad=True)

In [111]:
target = torch.empty(1, dtype=torch.long).random_(5)
target

tensor([2])

In [112]:
output = loss(input, target)
output

tensor(0.9671, grad_fn=<NllLossBackward0>)

In [113]:
torch.Tensor([1])

tensor([1.])