In [2]:
import torch
import numpy as np

In [22]:
tensor = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
], dtype=float)
print(tensor.shape, tensor.dtype, tensor.device)
print(tensor)

print(f"First row   : tensor[0]     = {tensor[0]}")
print(f"First column: tensor[:, 0]  = {tensor[:, 0]}")

print(f"Last row    : tensor[-1]    = {tensor[-1]}")
print(f"Last column : tensor[:, -1] = {tensor[:, -1]}")

tensor[:, 1] = 0
print(tensor)

torch.Size([3, 3]) torch.float64 cpu
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], dtype=torch.float64)
First row   : tensor[0]     = tensor([1., 2., 3.], dtype=torch.float64)
First column: tensor[:, 0]  = tensor([1., 4., 7.], dtype=torch.float64)
Last row    : tensor[-1]    = tensor([7., 8., 9.], dtype=torch.float64)
Last column : tensor[:, -1] = tensor([3., 6., 9.], dtype=torch.float64)
tensor([[1., 0., 3.],
        [4., 0., 6.],
        [7., 0., 9.]], dtype=torch.float64)


In [23]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

t2 = torch.stack([tensor, tensor, tensor], dim=1)
print(t2)

tensor([[1., 0., 3., 1., 0., 3., 1., 0., 3.],
        [4., 0., 6., 4., 0., 6., 4., 0., 6.],
        [7., 0., 9., 7., 0., 9., 7., 0., 9.]], dtype=torch.float64)
tensor([[[1., 0., 3.],
         [1., 0., 3.],
         [1., 0., 3.]],

        [[4., 0., 6.],
         [4., 0., 6.],
         [4., 0., 6.]],

        [[7., 0., 9.],
         [7., 0., 9.],
         [7., 0., 9.]]], dtype=torch.float64)


In [26]:
# 두 텐서 간의 행렬 곱(matrix multiplication)을 계산합니다. y1, y2, y3은 모두 같은 값을 갖습니다.
print(tensor, tensor.T)
y1 = tensor @ tensor.T
print(y1)

y2 = tensor.matmul(tensor.T)
print(y2)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)
print(y3)

tensor([[1., 0., 3.],
        [4., 0., 6.],
        [7., 0., 9.]], dtype=torch.float64) tensor([[1., 4., 7.],
        [0., 0., 0.],
        [3., 6., 9.]], dtype=torch.float64)
tensor([[ 10.,  22.,  34.],
        [ 22.,  52.,  82.],
        [ 34.,  82., 130.]], dtype=torch.float64)
tensor([[ 10.,  22.,  34.],
        [ 22.,  52.,  82.],
        [ 34.,  82., 130.]], dtype=torch.float64)
tensor([[ 10.,  22.,  34.],
        [ 22.,  52.,  82.],
        [ 34.,  82., 130.]], dtype=torch.float64)


In [27]:
agg = tensor.sum()
print
agg_item = agg.item()
print(agg, agg_item, type(agg_item))

tensor(30., dtype=torch.float64) 30.0 <class 'float'>
