In [5]:
import torch
from torch import nn
from torch import optim

In [6]:
x = torch.FloatTensor([
    [0, 1], [1, 2], [2, 3], [3, 4], [4, 5],
    [5, 6], [6, 7], [7, 8], [8, 9], [9, 0]
])
y = torch.FloatTensor([
    [0.94], [1.98], [2.88], [3.92], [3.96],
    [4.55], [5.64], [6.30], [7.44], [9.10]
])

model = nn.Linear(2, 1)
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.001)

for epoch in range(10000):
    y_pred = model(x)
    cost = criterion(y_pred, y)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if (epoch + 1) % 1000 == 0:
        print(f"Epoch : {epoch + 1:4d}, Model : {list(model.parameters())}, Cost : {cost:.3f}")

Epoch : 1000, Model : [Parameter containing:
tensor([[ 0.9027, -0.0814]], requires_grad=True), Parameter containing:
tensor([0.8838], requires_grad=True)], Cost : 0.099
Epoch : 2000, Model : [Parameter containing:
tensor([[ 0.8902, -0.0940]], requires_grad=True), Parameter containing:
tensor([1.0303], requires_grad=True)], Cost : 0.077
Epoch : 3000, Model : [Parameter containing:
tensor([[ 0.8821, -0.1021]], requires_grad=True), Parameter containing:
tensor([1.1237], requires_grad=True)], Cost : 0.068
Epoch : 4000, Model : [Parameter containing:
tensor([[ 0.8770, -0.1072]], requires_grad=True), Parameter containing:
tensor([1.1832], requires_grad=True)], Cost : 0.064
Epoch : 5000, Model : [Parameter containing:
tensor([[ 0.8738, -0.1105]], requires_grad=True), Parameter containing:
tensor([1.2211], requires_grad=True)], Cost : 0.063
Epoch : 6000, Model : [Parameter containing:
tensor([[ 0.8717, -0.1125]], requires_grad=True), Parameter containing:
tensor([1.2453], requires_grad=True)],