# Numpy Ops

In [1]:
import numpy as np

## [inner product](https://numpy.org/doc/stable/reference/generated/numpy.inner.html) ([kr](https://runebook.dev/ko/docs/numpy/reference/generated/numpy.inner))

* 두 행렬의 마지막 차원이 동일 해야함
* 연산 결과 두 행렬의 마지막 차원이 없어지며, 두 행렬의 차원이 합쳐짐
    - eg> $inner(x(5,4,3, 2), y(6,5,4,3,2) = z(5,4,3,6,5,4,3)$

### $inner(x(k,), y(k,)) = z()$
$\begin{align}
np.inner(x, y) = np.inner(\begin{bmatrix} 1 & 2 \end{bmatrix}, \begin{bmatrix} 10 & 20 \end{bmatrix})
&= 1 \times 10 + 2 \times 20 \\
&= 50
\end{align}$

In [14]:
x = np.array([1, 2])
print(f"x{x.shape} =", x, "\n")

y = np.array([10, 20])
print(f"y{y.shape} =", y, "\n")

z = np.inner(x, y)
print(f"np.inner(x, y) = z{z.shape} =", z, "\n")

try:
    z = x * y
    print(f"x * y = z{z.shape} =", z, "\n")
except Exception as e:
    print("Error x * y :", e, "\n")

try:
    z = np.dot(x, y)
    print(f"np.dot(x, y) = z{z.shape} =", z, "\n")
except Exception as e:
    print("Error np.dot(x, y) :", e, "\n")

x(2,) = [1 2] 

y(2,) = [10 20] 

np.inner(x, y) = z() = 50 

x * y = z(2,) = [10 40] 

np.dot(x, y) = z() = 50 



### $inner(x(n,), y(..., n)) = z(...)$
$\begin{align}
np.inner(x, y) = np.inner(\begin{bmatrix} 1 & 2 \end{bmatrix}
    ,
    \begin{bmatrix}
        10 & 20 \\
        30 & 40 \\
        50 & 60
    \end{bmatrix}
)
&= \begin{bmatrix}
    1 \times 10 + 2 \times 20 & 1 \times 30 + 2 \times 40 & 1 \times 50 + 2 \times 60
\end{bmatrix} \\
&= \begin{bmatrix} 50 & 110 & 170 \end{bmatrix}
\end{align}$

In [10]:
x = np.array([1, 2])
print(f"x{x.shape} =", x, "\n")

y = np.array([
    [10, 20],
    [30, 40],
    [50, 60],
])
print(f"y{y.shape} =", y, "\n")

z = np.inner(x, y)
print(f"np.inner(x, y) = z{z.shape} =", z, "\n")

try:
    z = np.dot(x, y)
    print(f"np.dot(x, y) = z{z.shape} =", z, "\n")
except Exception as e:
    print("Error :", e)

x(2,) = [1 2] 

y(3, 2) = [[10 20]
 [30 40]
 [50 60]] 

np.inner(x, y) = z(3,) = [ 50 110 170] 

Error : shapes (2,) and (3,2) not aligned: 2 (dim 0) != 3 (dim 0)


In [4]:
try:
    z = np.dot(x, y)
    print(f"np.dot(x, y) = z{z.shape} =", z)
except Exception as e:
    print("Error :", e)

Error : shapes (2,) and (3,2) not aligned: 2 (dim 0) != 3 (dim 0)


### $inner(x(..., k), y(..., k)) = z(..., ...)$
$\begin{align}
np.inner(x, y) = np.inner(
\begin{bmatrix}
    \begin{bmatrix} 1 & 2 \end{bmatrix} \\
    \begin{bmatrix} 3 & 4 \end{bmatrix} \\
    \begin{bmatrix} 5 & 6 \end{bmatrix}
\end{bmatrix}
,
\begin{bmatrix}
    \begin{bmatrix}
        \begin{bmatrix} 10 & 20 \end{bmatrix} \\
        \begin{bmatrix} 30 & 40 \end{bmatrix} \\
        \begin{bmatrix} 50 & 60 \end{bmatrix}
    \end{bmatrix} \\
    \begin{bmatrix}
        \begin{bmatrix} 100 & 200 \end{bmatrix} \\
        \begin{bmatrix} 300 & 400 \end{bmatrix} \\
        \begin{bmatrix} 500 & 600 \end{bmatrix}
    \end{bmatrix}
\end{bmatrix}
)
&= \begin{bmatrix}
    \begin{bmatrix}
        \begin{bmatrix}
            1 \times 10 + 2 \times 20 & 1 \times 30 + 2 \times 40 & 1 \times 50 + 2 \times 60
        \end{bmatrix} \\
        \begin{bmatrix}
            1 \times 100 + 2 \times 200 & 1 \times 300 + 2 \times 400 & 1 \times 500 + 2 \times 600
        \end{bmatrix}
    \end{bmatrix} \\
    \begin{bmatrix}
        \begin{bmatrix}
            3 \times 10 + 4 \times 20 & 3 \times 30 + 4 \times 40 & 3 \times 50 + 4 \times 60
        \end{bmatrix} \\
        \begin{bmatrix}
            3 \times 100 + 4 \times 200 & 3 \times 300 + 4 \times 400 & 3 \times 500 + 4 \times 600
        \end{bmatrix}
    \end{bmatrix} \\
    \begin{bmatrix}
        \begin{bmatrix}
            5 \times 10 + 6 \times 20 & 5 \times 30 + 6 \times 40 & 5 \times 50 + 6 \times 60
        \end{bmatrix} \\
        \begin{bmatrix}
            5 \times 100 + 6 \times 200 & 5 \times 300 + 6 \times 400 & 5 \times 500 + 6 \times 600
        \end{bmatrix}
    \end{bmatrix}
\end{bmatrix} \\
&= \begin{bmatrix}
    \begin{bmatrix}
        \begin{bmatrix}
            50 & 110 & 170
        \end{bmatrix} \\
        \begin{bmatrix}
            500 & 1100 & 1700
        \end{bmatrix}
    \end{bmatrix} \\
    \begin{bmatrix}
        \begin{bmatrix}
            110 & 250 & 390
        \end{bmatrix} \\
        \begin{bmatrix}
            1100 & 2500 & 3900
        \end{bmatrix}
    \end{bmatrix} \\
    \begin{bmatrix}
        \begin{bmatrix}
            170 & 390 & 610
        \end{bmatrix} \\
        \begin{bmatrix}
            1700 & 3900 & 6100
        \end{bmatrix}
    \end{bmatrix}
\end{bmatrix}
\end{align}$

In [5]:
x = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
])
print(f"x{x.shape} =", x)

y = np.array([
    [
        [10, 20],
        [30, 40],
        [50, 60],
    ],
    [
        [100, 200],
        [300, 400],
        [500, 600],
    ]
])
print(f"y{y.shape} =", y)

z = np.inner(x, y)
print(f"np.inner(x, y) = z{z.shape} =", z)

x(3, 2) = [[1 2]
 [3 4]
 [5 6]]
y(2, 3, 2) = [[[ 10  20]
  [ 30  40]
  [ 50  60]]

 [[100 200]
  [300 400]
  [500 600]]]
np.inner(x, y) = z(3, 2, 3) = [[[  50  110  170]
  [ 500 1100 1700]]

 [[ 110  250  390]
  [1100 2500 3900]]

 [[ 170  390  610]
  [1700 3900 6100]]]


In [6]:
try:
    z = np.dot(x, y)
    print(f"np.dot(x, y) = z{z.shape} =", z)
except Exception as e:
    print("Error :", e)

Error : shapes (3,2) and (2,3,2) not aligned: 2 (dim 1) != 3 (dim 1)
