# Numpy Ops

In [84]:
import numpy as np

## [matmul product](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html) ([kr](https://runebook.dev/ko/docs/numpy/reference/generated/numpy.matmul))
* 첫 행렬의 마지막 차원과, 두번째 행렬의 끝에서 두번째 차원의 크기가 동일 해야함
* 연산 결과 두 행렬의 연산 차원이 없어지며, 두 행렬의 차원이 합쳐짐
    - eg> $inner(x(5,4,3,2), y(6,5,4,2,3) = z(5,4,3,6,5,4,3)$

cf> dot product

### $matmul(x(k,), y(k,)) = z()$
$\begin{align}
np.matmul(x, y) = np.matmul(
    \begin{bmatrix} 1 & 2 \end{bmatrix}
    ,
    \begin{bmatrix}
        10 \\
        20
    \end{bmatrix})
&= 1 \times 10 + 2 \times 20 \\
&= 50
\end{align}$

In [85]:
x = np.array([1, 2])
print(f"x{x.shape} =", x, "\n")

y = np.array([10, 20])
print(f"y{y.shape} =", y, "\n")

z = np.matmul(x, y)
print(f"np.matmul(x, y) = z{z.shape} =", z, "\n")

z = np.dot(x, y)
print(f"np.dot(x, y) = z{z.shape} =", z, "\n")

x(2,) = [1 2] 

y(2,) = [10 20] 

np.matmul(x, y) = z() = 50 

np.dot(x, y) = z() = 50 



---
### dim < 3 : $matmul(x(l, k), y(k, n)) = z(l, n)$
$\begin{align}
np.matmul(x, y) = np.matmul(
    \begin{bmatrix}
        \begin{bmatrix} 1 & 2 \end{bmatrix} \\
        \begin{bmatrix} 3 & 4 \end{bmatrix} \\
        \begin{bmatrix} 5 & 6 \end{bmatrix} \\
    \end{bmatrix}
    ,
    \begin{bmatrix}
        10 & 20 & 30 \\
        40 & 50 & 60 \\
    \end{bmatrix}
)
&=  \begin{bmatrix}
        \begin{bmatrix} 1 \times 10 + 2 \times 40   & 1 \times 20 + 2 \times 50     & 1 \times 30 + 2 \times 60   \end{bmatrix} \\
        \begin{bmatrix} 3 \times 10 + 4 \times 40   & 3 \times 20 + 4 \times 50     & 3 \times 30 + 4 \times 60   \end{bmatrix} \\
        \begin{bmatrix} 5 \times 10 + 6 \times 40   & 5 \times 20 + 6 \times 50     & 5 \times 30 + 6 \times 60   \end{bmatrix} \\
    \end{bmatrix} \\
&=  \begin{bmatrix}
        \begin{bmatrix}  90 & 120 & 150 \end{bmatrix} \\
        \begin{bmatrix} 190 & 260 & 330 \end{bmatrix} \\
        \begin{bmatrix} 290 & 400 & 510 \end{bmatrix} \\
    \end{bmatrix}
\end{align}$

In [86]:
x = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
print(f"x{x.shape} =", x, "\n")

y = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print(f"y{y.shape} =", y, "\n")

z = np.matmul(x, y)
print(f"np.matmul(x, y) = z{z.shape} =", z, "\n")

z = np.dot(x, y)
print(f"np.dot(x, y) = z{z.shape} =", z, "\n")

x(3, 2) = [[1 2]
 [3 4]
 [5 6]] 

y(2, 3) = [[10 20 30]
 [40 50 60]] 

np.matmul(x, y) = z(3, 3) = [[ 90 120 150]
 [190 260 330]
 [290 400 510]] 

np.dot(x, y) = z(3, 3) = [[ 90 120 150]
 [190 260 330]
 [290 400 510]] 



In [87]:
x = np.ones([5, 4, 3, 2])
print(f"x{x.shape}\n")

y = np.ones([5, 4, 2, 3])
print(f"y{y.shape}\n")

z = np.matmul(x, y)
print(f"z{z.shape}\n")

x(5, 4, 3, 2)

y(5, 4, 2, 3)

z(5, 4, 3, 3)



---
### dim >= 3 : $matmul(x(l(or 1), n+, k), y(l(or 1), n+, k, m)) = z(l, n+, m)$
$\begin{align}
np.matmul(x, y) = np.matmul(
    \begin{bmatrix}
        \begin{bmatrix}
            \begin{bmatrix} 1 & 2 \end{bmatrix} \\
            \begin{bmatrix} 3 & 4 \end{bmatrix} \\
            \begin{bmatrix} 5 & 6 \end{bmatrix} \\
        \end{bmatrix} \\
        \begin{bmatrix}
            \begin{bmatrix} 10 & 20 \end{bmatrix} \\
            \begin{bmatrix} 30 & 40 \end{bmatrix} \\
            \begin{bmatrix} 50 & 60 \end{bmatrix} \\
        \end{bmatrix}
    \end{bmatrix}
    ,
    \begin{bmatrix}
        \begin{bmatrix}
            \begin{bmatrix} 10 & 20 \end{bmatrix} \\
            \begin{bmatrix} 30 & 40 \end{bmatrix} \\
        \end{bmatrix} \\
        \begin{bmatrix}
            \begin{bmatrix} 50 & 60 \end{bmatrix} \\
            \begin{bmatrix} 70 & 80 \end{bmatrix} \\
        \end{bmatrix}
    \end{bmatrix}
)
&=  \begin{bmatrix}
        \begin{bmatrix}
            \begin{bmatrix}
                \begin{bmatrix} 1 & 2 \end{bmatrix} \\
                \begin{bmatrix} 3 & 4 \end{bmatrix} \\
                \begin{bmatrix} 5 & 6 \end{bmatrix} \\
            \end{bmatrix}
            \cdot
            \begin{bmatrix}
                \begin{bmatrix} 10 & 20 \end{bmatrix} \\
                \begin{bmatrix} 30 & 40 \end{bmatrix} \\
            \end{bmatrix}
        \end{bmatrix} \\
        \begin{bmatrix}
            \begin{bmatrix}
                \begin{bmatrix} 10 & 20 \end{bmatrix} \\
                \begin{bmatrix} 30 & 40 \end{bmatrix} \\
                \begin{bmatrix} 50 & 60 \end{bmatrix} \\
            \end{bmatrix}
            \cdot
            \begin{bmatrix}
                \begin{bmatrix} 50 & 60 \end{bmatrix} \\
                \begin{bmatrix} 70 & 80 \end{bmatrix} \\
            \end{bmatrix}
        \end{bmatrix} \\
    \end{bmatrix} \\
&=  \begin{bmatrix}
        \begin{bmatrix}
            \begin{bmatrix} 1 \times 10 + 2 \times 30   &   1 \times 20 + 2 \times 40   \end{bmatrix} \\
            \begin{bmatrix} 3 \times 10 + 4 \times 30   &   3 \times 20 + 4 \times 40   \end{bmatrix} \\
            \begin{bmatrix} 5 \times 10 + 6 \times 30   &   5 \times 20 + 6 \times 40   \end{bmatrix} \\
        \end{bmatrix} \\
        \begin{bmatrix}
            \begin{bmatrix} 10 \times 50 + 20 \times 70   &   10 \times 60 + 20 \times 80   \end{bmatrix} \\
            \begin{bmatrix} 30 \times 50 + 40 \times 70   &   30 \times 60 + 40 \times 80   \end{bmatrix} \\
            \begin{bmatrix} 50 \times 50 + 60 \times 70   &   50 \times 60 + 60 \times 80   \end{bmatrix} \\
        \end{bmatrix} \\
    \end{bmatrix} \\
&=  \begin{bmatrix}
        \begin{bmatrix}
            \begin{bmatrix} 70  & 100   \end{bmatrix} \\
            \begin{bmatrix} 170 & 220   \end{bmatrix} \\
            \begin{bmatrix} 230 & 340   \end{bmatrix} \\
        \end{bmatrix} \\
        \begin{bmatrix}
            \begin{bmatrix} 1900    & 2200   \end{bmatrix} \\
            \begin{bmatrix} 4300    & 5000   \end{bmatrix} \\
            \begin{bmatrix} 6700    & 7800   \end{bmatrix} \\
        \end{bmatrix} \\
    \end{bmatrix}
\end{align}$

In [88]:
 x = np.array([
    [[1, 2], [3, 4], [5, 6]],
    [[10, 20], [30, 40], [50, 60]],
])
print(f"x{x.shape} =", x, "\n")

y = np.array([
    [[10, 20], [30, 40]],
    [[50, 60], [70, 80]],
])
print(f"y{y.shape} =", y, "\n")

z = np.matmul(x, y)
print(f"np.matmul(x, y) = z{z.shape} =", z, "\n")

z = np.dot(x, y)
print(f"np.dot(x, y) = z{z.shape} =", z, "\n")

x(2, 3, 2) = [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[10 20]
  [30 40]
  [50 60]]] 

y(2, 2, 2) = [[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]] 

np.matmul(x, y) = z(2, 3, 2) = [[[  70  100]
  [ 150  220]
  [ 230  340]]

 [[1900 2200]
  [4300 5000]
  [6700 7800]]] 

np.dot(x, y) = z(2, 3, 2, 2) = [[[[  70  100]
   [ 190  220]]

  [[ 150  220]
   [ 430  500]]

  [[ 230  340]
   [ 670  780]]]


 [[[ 700 1000]
   [1900 2200]]

  [[1500 2200]
   [4300 5000]]

  [[2300 3400]
   [6700 7800]]]] 



In [89]:
x = np.array([
    [
        [1, 2],
        [1, 2],
    ],
    [
        [5, 6],
        [5, 6]
    ],
    [
        [7, 8],
        [7, 8],
    ],
])
print(f"x{x.shape} =", x)

y = np.array([
    [
        [10, 20, 30, 40],
        [40, 50, 60, 60],
    ],
    [
        [100, 200, 300, 400],
        [400, 500, 600, 600],
    ],
    [
        [100, 200, 300, 400],
        [400, 500, 600, 600],
    ]
])
print(f"y{y.shape} =", y)

z = np.matmul(x, y)
print(f"np.matmul(x, y) = z{z.shape} =", z)

z = np.dot(x, y)
print(f"np.dot(x, y) = z{z.shape} =", z)

x(3, 2, 2) = [[[1 2]
  [1 2]]

 [[5 6]
  [5 6]]

 [[7 8]
  [7 8]]]
y(3, 2, 4) = [[[ 10  20  30  40]
  [ 40  50  60  60]]

 [[100 200 300 400]
  [400 500 600 600]]

 [[100 200 300 400]
  [400 500 600 600]]]
np.matmul(x, y) = z(3, 2, 4) = [[[  90  120  150  160]
  [  90  120  150  160]]

 [[2900 4000 5100 5600]
  [2900 4000 5100 5600]]

 [[3900 5400 6900 7600]
  [3900 5400 6900 7600]]]
np.dot(x, y) = z(3, 2, 3, 4) = [[[[  90  120  150  160]
   [ 900 1200 1500 1600]
   [ 900 1200 1500 1600]]

  [[  90  120  150  160]
   [ 900 1200 1500 1600]
   [ 900 1200 1500 1600]]]


 [[[ 290  400  510  560]
   [2900 4000 5100 5600]
   [2900 4000 5100 5600]]

  [[ 290  400  510  560]
   [2900 4000 5100 5600]
   [2900 4000 5100 5600]]]


 [[[ 390  540  690  760]
   [3900 5400 6900 7600]
   [3900 5400 6900 7600]]

  [[ 390  540  690  760]
   [3900 5400 6900 7600]
   [3900 5400 6900 7600]]]]
