In [207]:
import numpy as np
import torch
import torch.nn as nn
from torch import Tensor, optim
from sklearn.preprocessing import MinMaxScaler

torch.manual_seed(1)  # 난수 고정
torch.set_printoptions(threshold=10, linewidth=128)  # for printing

In [208]:
scaler = MinMaxScaler()

time_steps = 3


def build_dataset(data, time_steps: int = 3):
    x, y = [], []
    for i in range(time_steps, len(data)):
        x.append(data[i - time_steps:i])
        y.append(data[i])
    return torch.FloatTensor(np.array(x)).unsqueeze(dim=2), torch.FloatTensor(np.array(y)).unsqueeze(dim=1)


x_train, y_train = build_dataset(data=np.linspace(1, 10, 10, dtype=float))
print(x_train, y_train)

x_test, y_test = build_dataset(data=np.linspace(11, 20, 10, dtype=float))
print(x_test, y_test)

tensor([[[1.],
         [2.],
         [3.]],

        [[2.],
         [3.],
         [4.]],

        [[3.],
         [4.],
         [5.]],

        ...,

        [[5.],
         [6.],
         [7.]],

        [[6.],
         [7.],
         [8.]],

        [[7.],
         [8.],
         [9.]]]) tensor([[ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])
tensor([[[11.],
         [12.],
         [13.]],

        [[12.],
         [13.],
         [14.]],

        [[13.],
         [14.],
         [15.]],

        ...,

        [[15.],
         [16.],
         [17.]],

        [[16.],
         [17.],
         [18.]],

        [[17.],
         [18.],
         [19.]]]) tensor([[14.],
        [15.],
        [16.],
        [17.],
        [18.],
        [19.],
        [20.]])


In [221]:
model = nn.RNN(input_size=1, hidden_size=5, num_layers=1, nonlinearity='relu')
criterion = nn.MSELoss()  # nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), 0.01)
for e in range(20):
    for i, x in enumerate(x_train):
        o, _ = model(x)
        z = o[-1, -1:]
        cost = criterion(z, y_train[i])
        optimizer.zero_grad()
        cost.backward()
        optimizer.step()
    print(z, y_train[i], cost)

tensor([1.6429], grad_fn=<SliceBackward0>) tensor([10.]) tensor(69.8413, grad_fn=<MseLossBackward0>)
tensor([2.7217], grad_fn=<SliceBackward0>) tensor([10.]) tensor(52.9735, grad_fn=<MseLossBackward0>)
tensor([3.5813], grad_fn=<SliceBackward0>) tensor([10.]) tensor(41.1998, grad_fn=<MseLossBackward0>)
tensor([4.2953], grad_fn=<SliceBackward0>) tensor([10.]) tensor(32.5436, grad_fn=<MseLossBackward0>)
tensor([4.9774], grad_fn=<SliceBackward0>) tensor([10.]) tensor(25.2269, grad_fn=<MseLossBackward0>)
tensor([5.7191], grad_fn=<SliceBackward0>) tensor([10.]) tensor(18.3259, grad_fn=<MseLossBackward0>)
tensor([6.5146], grad_fn=<SliceBackward0>) tensor([10.]) tensor(12.1477, grad_fn=<MseLossBackward0>)
tensor([7.3692], grad_fn=<SliceBackward0>) tensor([10.]) tensor(6.9212, grad_fn=<MseLossBackward0>)
tensor([8.2853], grad_fn=<SliceBackward0>) tensor([10.]) tensor(2.9402, grad_fn=<MseLossBackward0>)
tensor([9.2177], grad_fn=<SliceBackward0>) tensor([10.]) tensor(0.6121, grad_fn=<MseLossBackw

In [222]:
with torch.no_grad():
    for i, x in enumerate(x_test):
        o, _ = model(x)
        z = o[-1, -1:]
        print(x, z, z.round(), y_test[i])

tensor([[11.],
        [12.],
        [13.]]) tensor([14.0702]) tensor([14.]) tensor([14.])
tensor([[12.],
        [13.],
        [14.]]) tensor([15.0773]) tensor([15.]) tensor([15.])
tensor([[13.],
        [14.],
        [15.]]) tensor([16.0844]) tensor([16.]) tensor([16.])
tensor([[14.],
        [15.],
        [16.]]) tensor([17.0915]) tensor([17.]) tensor([17.])
tensor([[15.],
        [16.],
        [17.]]) tensor([18.0986]) tensor([18.]) tensor([18.])
tensor([[16.],
        [17.],
        [18.]]) tensor([19.1056]) tensor([19.]) tensor([19.])
tensor([[17.],
        [18.],
        [19.]]) tensor([20.1127]) tensor([20.]) tensor([20.])
