In [1]:
import torch
from torch import nn
from torch import optim

In [2]:
x = torch.FloatTensor([
    [0, 1], [1, 2], [2, 3], [3, 4], [4, 5],
    [5, 6], [6, 7], [7, 8], [8, 9], [9, 0]
])
y = torch.FloatTensor([
    [0.94], [1.98], [2.88], [3.92], [3.96],
    [4.55], [5.64], [6.30], [7.44], [9.10]
])

model = nn.Linear(2, 1)
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.001)

for epoch in range(10000):
    y_pred = model(x)
    cost = criterion(y_pred, y)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if (epoch + 1) % 1000 == 0:
        print(f"Epoch : {epoch + 1:4d}, Model : {list(model.parameters())}, Cost : {cost:.3f}")

Epoch : 1000, Model : [Parameter containing:
tensor([[ 0.9476, -0.0366]], requires_grad=True), Parameter containing:
tensor([0.3636], requires_grad=True)], Cost : 0.257
Epoch : 2000, Model : [Parameter containing:
tensor([[ 0.9187, -0.0655]], requires_grad=True), Parameter containing:
tensor([0.6989], requires_grad=True)], Cost : 0.141
Epoch : 3000, Model : [Parameter containing:
tensor([[ 0.9003, -0.0839]], requires_grad=True), Parameter containing:
tensor([0.9125], requires_grad=True)], Cost : 0.094
Epoch : 4000, Model : [Parameter containing:
tensor([[ 0.8886, -0.0956]], requires_grad=True), Parameter containing:
tensor([1.0486], requires_grad=True)], Cost : 0.075
Epoch : 5000, Model : [Parameter containing:
tensor([[ 0.8811, -0.1031]], requires_grad=True), Parameter containing:
tensor([1.1354], requires_grad=True)], Cost : 0.067
Epoch : 6000, Model : [Parameter containing:
tensor([[ 0.8764, -0.1078]], requires_grad=True), Parameter containing:
tensor([1.1906], requires_grad=True)],