In [14]:
import torch
import torch.nn as nn
from torch import Tensor, optim

torch.manual_seed(1)  # 난수 고정
torch.set_printoptions(threshold=10, linewidth=128)  # for printing

In [15]:
data = torch.Tensor([
    [1],
    [2],
    [3],
    [4],
    [5],
    [6]
])
x = data[:3]
print(x.shape, x)

y = data[3:]
print(y.shape, y)

torch.Size([3, 1]) tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1]) tensor([[4.],
        [5.],
        [6.]])


In [37]:
model = model = nn.Linear(in_features=1, out_features=1)
criterion = nn.MSELoss()  # nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), 0.01)
for e in range(1000):
    for i, xi in enumerate(x):
        z = model(xi)
        cost = criterion(z, y[i])
        #print(xi, z.shape, z, y[i], cost)

        optimizer.zero_grad()
        cost.backward()
        optimizer.step()

In [38]:
with torch.no_grad():
    print(model(Tensor([1])).round())
    print(model(Tensor([2])).round())
    print(model(Tensor([3])).round())
    print(model(Tensor([4])).round())
    print(model(Tensor([5])).round())
    print(model(Tensor([6])).round())

tensor([4.])
tensor([5.])
tensor([6.])
tensor([7.])
tensor([8.])
tensor([9.])
