In [52]:
import numpy as np

In [53]:
x = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ],
    [
        [9, 10],
        [11, 12]
    ]
])
print(x)
print(x.shape)

print("\n", np.sum(x, axis=0))
print("\n", np.sum(x, axis=1))
print("\n", np.sum(x, axis=2))

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
(3, 2, 2)

 [[15 18]
 [21 24]]

 [[ 4  6]
 [12 14]
 [20 22]]

 [[ 3  7]
 [11 15]
 [19 23]]


In [59]:
a = np.linspace(1, 5, 5, endpoint=True, dtype="int")
print(a)
print(a.shape)

[1 2 3 4 5]
(5,)


In [58]:
a0 = np.expand_dims(a, axis=0)
print(a0)
print(a0.shape)

a1 = np.expand_dims(a, axis=1)
print(a1)
print(a1.shape)

[[0 1 2 3 4 5]]
(1, 6)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
(6, 1)


In [62]:
b = np.linspace(6, 10, 5, endpoint=True, dtype="int")

r_ab = np.r_[a, b]
print(r_ab)

hstack_ab = np.hstack([a, b])
print(hstack_ab)

con_ab = np.concatenate((a, b), axis=0)
print(con_ab)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [68]:
b = np.linspace(6, 10, 5, endpoint=True, dtype="int")

r_ab = np.r_[[a], [b]]
print(r_ab)

vstack_ab = np.vstack([a, b])
print(vstack_ab)

con0_ab = np.concatenate((r_ab, vstack_ab), axis=0)
print(con0_ab)

con1_ab = np.concatenate((r_ab, vstack_ab), axis=1)
print(con1_ab)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5  1  2  3  4  5]
 [ 6  7  8  9 10  6  7  8  9 10]]


In [72]:
b = np.linspace(6, 10, 5, endpoint=True, dtype="int")

c_ab = np.c_[a, b]
print(c_ab)

cstack_ab = np.column_stack([a, b])
print(cstack_ab)

print(c_ab.T)
print(cstack_ab.T)
con0_ab = np.concatenate((c_ab.T, cstack_ab.T), axis=0)
print(con0_ab)

con1_ab = np.concatenate((c_ab.T, cstack_ab.T), axis=1)
print(con1_ab)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5  1  2  3  4  5]
 [ 6  7  8  9 10  6  7  8  9 10]]


In [73]:
print(np.c_[np.array([[1, 2, 3]]), 0, 0, np.array([[4, 5, 6]])])

[[1 2 3 0 0 4 5 6]]
