In [2]:
import torch
from torch import nn
from torch import optim

torch.manual_seed(777)
if torch.cuda.is_available():
    device = 'cuda'
    torch.cuda.manual_seed_all(777)
else:
    device = 'cpu'

In [26]:
x = torch.FloatTensor([[0, 0], [0, 1], [1, 0], [1, 1]]).to(device)
y_and = torch.FloatTensor([[0], [0], [0], [1]]).to(device)
y_nand = torch.FloatTensor([[1], [1], [1], [0]]).to(device)
y_or = torch.FloatTensor([[0], [1], [1], [1]]).to(device)
y_xor = torch.FloatTensor([[0], [1], [1], [0]]).to(device)


class GateModel(nn.Module):
    def __init__(self):
        super(GateModel, self).__init__()
        self.layer = nn.Sequential(
            nn.Linear(2, 1, bias=True),
            nn.Sigmoid()  # covert between 0 to 1
        )

    def forward(self, x):
        return self.layer(x)


model = GateModel().to(device)
criterion = nn.BCELoss().to(device)
optimizer = torch.optim.SGD(model.parameters(), lr=1)


def train(x, y, model=model, criterion=criterion, optimizer=optimizer):
    model.layer[0].reset_parameters()

    print("\nStart ...")
    for epoch in range(100):
        output = model(x)
        loss = criterion(output, y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if (epoch + 1) % 10 == 0:
            print(f"Epoch : {epoch + 1:4d}, Cost : {loss:.3f}")

    for param in model.parameters():
        print(param)

    with torch.no_grad():
        model.eval()
        print("x =", x)
        print("o = ", model(x) > 0.5)
        print("y =", y)
    print("Finished !!!\n")


train(x, y_and)
train(x, y_or)
train(x, y_nand)
train(x, y_xor)


Start ...
Epoch :   10, Cost : 0.506
Epoch :   20, Cost : 0.387
Epoch :   30, Cost : 0.316
Epoch :   40, Cost : 0.270
Epoch :   50, Cost : 0.236
Epoch :   60, Cost : 0.210
Epoch :   70, Cost : 0.189
Epoch :   80, Cost : 0.172
Epoch :   90, Cost : 0.158
Epoch :  100, Cost : 0.146
Parameter containing:
tensor([[3.0177, 3.0128]], requires_grad=True)
Parameter containing:
tensor([-4.7408], requires_grad=True)
x = tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])
o =  tensor([[False],
        [False],
        [False],
        [ True]])
y = tensor([[0.],
        [0.],
        [0.],
        [1.]])
Finished !!!


Start ...
Epoch :   10, Cost : 0.376
Epoch :   20, Cost : 0.288
Epoch :   30, Cost : 0.231
Epoch :   40, Cost : 0.192
Epoch :   50, Cost : 0.164
Epoch :   60, Cost : 0.142
Epoch :   70, Cost : 0.126
Epoch :   80, Cost : 0.112
Epoch :   90, Cost : 0.101
Epoch :  100, Cost : 0.092
Parameter containing:
tensor([[3.9893, 3.9684]], requires_grad=True)
Parameter cont