# Numpy Ops

In [8]:
import numpy as np

## [outer product](https://numpy.org/doc/stable/reference/generated/numpy.outer.html) ([kr](https://runebook.dev/ko/docs/numpy/reference/generated/numpy.outer))

* 첫번째 행렬의 모든 항목을 순회 하며, 두번째 행렬의 모든 항목과 각각 곱셉 연산 한다.
* 결과 차원은 (첫번째 행렬의 모든 항목의 개수 = 차원 크기의 곱, 두번째 행렬의 모든 항목의 개수 = 차원 크기의 곱)
    - eg> $inner(x(1,2,3), y(4,5,6) = z(6,120)$

### $outer(x(n,), y(n,)) = z(n, n)$
$\begin{align}
np.outer(x, y) = np.outer(\begin{bmatrix} 1 & 2 \end{bmatrix}, \begin{bmatrix} 10 & 20 & 30 \end{bmatrix})
&= \begin{bmatrix}
    \begin{bmatrix} 1 \times 10 & 1 \times 20 & 1 \times 30 \end{bmatrix} \\
    \begin{bmatrix} 2 \times 10 & 2 \times 20 & 2 \times 30 \end{bmatrix} \\
\end{bmatrix}
&= \begin{bmatrix}
    \begin{bmatrix} 10 & 20 & 30 \end{bmatrix} \\
    \begin{bmatrix} 20 & 40 & 60 \end{bmatrix} \\
\end{bmatrix}
\end{align}$

In [9]:
x = np.array([1, 2])
print(f"x{x.shape} =", x)

y = np.array([10, 20, 30])
print(f"y{y.shape} =", y)

z = np.outer(x, y)
print(f"np.outer(x, y) = z{z.shape} =", z)

x(2,) = [1 2]
y(3,) = [10 20 30]
np.outer(x, y) = z(2, 3) = [[10 20 30]
 [20 40 60]]


### $outer(x(n,), y(l, ..., m)) = z(n, l * ... * m)$
$\begin{align}
np.inner(x, y) = outer(\begin{bmatrix} 1 & 2 \end{bmatrix}
    ,
    \begin{bmatrix}
        10 & 20 \\
        30 & 40 \\
        50 & 60
    \end{bmatrix}
)
&= \begin{bmatrix}
    \begin{bmatrix}
        1 \times 10 & 1 \times 20 & 1 \times 30 & 1 \times 40 & 1 \times 50 & 1 \times 60
    \end{bmatrix} \\
    \begin{bmatrix}
        2 \times 10 & 2 \times 20 & 2 \times 30 & 2 \times 40 & 2 \times 50 & 2 \times 60
    \end{bmatrix}
\end{bmatrix} \\
&= \begin{bmatrix}
    \begin{bmatrix}
        10 & 20 & 30 & 40 & 50 & 60
    \end{bmatrix} \\
    \begin{bmatrix}
        20 & 40 & 60 & 80 & 100 & 120
    \end{bmatrix}
\end{bmatrix}
\end{align}$

In [10]:
x = np.array([1, 2])
print(f"x{x.shape} =", x)

y = np.array([
    [10, 20],
    [30, 40],
    [50, 60],
])
print(f"y{y.shape} =", y)

z = np.outer(x, y)
print(f"np.outer(x, y) = z{z.shape} =", z)

x(2,) = [1 2]
y(3, 2) = [[10 20]
 [30 40]
 [50 60]]
np.outer(x, y) = z(2, 6) = [[ 10  20  30  40  50  60]
 [ 20  40  60  80 100 120]]


### $inner(x(l, ..., m), y(n, ..., o)) = z(l * ... * m, n * ... * o)$
$\begin{align}
np.outer(x, y) = np.outer(
\begin{bmatrix}
    \begin{bmatrix} 1 & 2 \end{bmatrix} \\
    \begin{bmatrix} 3 & 4 \end{bmatrix}
\end{bmatrix}
,
\begin{bmatrix}
    \begin{bmatrix}
        \begin{bmatrix} 10 & 20 \end{bmatrix} \\
        \begin{bmatrix} 30 & 40 \end{bmatrix}
    \end{bmatrix} \\
    \begin{bmatrix}
        \begin{bmatrix} 100 & 200 \end{bmatrix} \\
        \begin{bmatrix} 300 & 400 \end{bmatrix}
    \end{bmatrix}
\end{bmatrix}
&= \begin{bmatrix}
    \begin{bmatrix}
        1 \times 10     & 1 \times 20   & 1 \times 30   & 1 \times 40
        &
        1 \times 100    & 1 \times 200  & 1 \times 300  & 1 \times 400
    \end{bmatrix} \\
    \begin{bmatrix}
        2 \times 10     & 2 \times 20   & 2 \times 30   & 2 \times 40
        &
        2 \times 100    & 2 \times 200  & 2 \times 300  & 2 \times 400
    \end{bmatrix} \\
    \begin{bmatrix}
        3 \times 10     & 3 \times 20   & 3 \times 30   & 3 \times 40
        &
        3 \times 100    & 3 \times 200  & 3 \times 300  & 3 \times 400
    \end{bmatrix} \\
    \begin{bmatrix}
        4 \times 10     & 4 \times 20   & 4 \times 30   & 4 \times 40
        &
        4 \times 100    & 4 \times 200  & 4 \times 300  & 4 \times 400
    \end{bmatrix}
\end{bmatrix} \\
&= \begin{bmatrix}
    \begin{bmatrix}
        10  & 20    & 30    & 40    & 100   & 200   & 300   & 400
    \end{bmatrix} \\
    \begin{bmatrix}
        20  & 40    & 60    & 80    & 200   & 400   & 600   & 800
    \end{bmatrix} \\
    \begin{bmatrix}
        30  & 60    & 90    & 120   & 300   & 600   & 900   & 1200
    \end{bmatrix} \\
    \begin{bmatrix}
        40  & 80    & 120   & 160   & 400   & 800   & 1200  & 1600
    \end{bmatrix}
\end{bmatrix}
\end{align}$

In [11]:
x = np.array([
    [1, 2],
    [3, 4]
])
print(f"x{x.shape} =", x)

y = np.array([
    [
        [10, 20],
        [30, 40],
    ],
    [
        [100, 200],
        [300, 400],
    ]
])
print(f"y{y.shape} =", y)

z = np.outer(x, y)
print(f"np.outer(x, y) = z{z.shape} =", z)

x(2, 2) = [[1 2]
 [3 4]]
y(2, 2, 2) = [[[ 10  20]
  [ 30  40]]

 [[100 200]
  [300 400]]]
np.outer(x, y) = z(4, 8) = [[  10   20   30   40  100  200  300  400]
 [  20   40   60   80  200  400  600  800]
 [  30   60   90  120  300  600  900 1200]
 [  40   80  120  160  400  800 1200 1600]]
