In [118]:
import numpy as np


def algebra(x, y, all=False, basic=False, algebra=True, mat=False):
    x = np.array(x)
    y = np.array(y)
    print(f"x{x.shape} =", x, "\n")
    print(f"y{y.shape} =", y, "\n")
    result = {}
    if all or basic:
        try:
            result['sum'] = z = x + y
            print(f"x + y = {x.shape} + {y.shape} = z{z.shape} =", z, "\n")
        except Exception as e:
            print("Error x + y :", e, "\n")

        try:
            result['product'] = z = x * y
            print(f"x * y = z{z.shape} =", z, "\n")
        except Exception as e:
            print("Error x * y :", e, "\n")

        try:
            result['division'] = z = x / y
            print(f"x / y = z{z.shape} =", z, "\n")
        except Exception as e:
            print("Error x / y :", e, "\n")
        pass

    if (all or algebra) and not mat:
        try:
            result['inner'] = z = np.inner(x, y)
            print(f"np.inner(x, y) \n= np.inner({x.shape}, {y.shape}) = z{z.shape} \n=", z, "\n")
        except Exception as e:
            print("Error np.inner(x, y) :", e, "\n")

        try:
            result['outer'] = z = np.outer(x, y)
            print(f"np.outer(x, y) \n= np.outer({x.shape}, {y.shape}) = z{z.shape} \n=", z, "\n")
        except Exception as e:
            print("Error np.outer(x, y) :", e, "\n")

    if all or algebra or mat:
        try:
            result['dot'] = z = np.dot(x, y)
            print(f"np.dot(x, y) \n= np.dot({x.shape}, {y.shape}) = z{z.shape} \n=", z, "\n")
        except Exception as e:
            print("Error np.dot(x, y) :", e, "\n")

        try:
            result['matmul'] = z = np.matmul(x, y)
            print(f"np.matmul(x, y) \n= np.matmul({x.shape}, {y.shape}) = z{z.shape} \n=", z, "\n")
        except Exception as e:
            print("Error np.matmul(x, y) :", e, "\n")

    #return result

In [119]:
algebra(
    [1, 2],
    [10, 20]
)

x(2,) = [1 2] 

y(2,) = [10 20] 

np.inner(x, y) 
= np.inner((2,), (2,)) = z() 
= 50 

np.outer(x, y) 
= np.outer((2,), (2,)) = z(2, 2) 
= [[10 20]
 [20 40]] 

np.dot(x, y) 
= np.dot((2,), (2,)) = z() 
= 50 

np.matmul(x, y) 
= np.matmul((2,), (2,)) = z() 
= 50 



In [120]:
algebra(
    [
        [1, 2],
        [3, 4]
    ],
    [10, 20]
)

x(2, 2) = [[1 2]
 [3 4]] 

y(2,) = [10 20] 

np.inner(x, y) 
= np.inner((2, 2), (2,)) = z(2,) 
= [ 50 110] 

np.outer(x, y) 
= np.outer((2, 2), (2,)) = z(4, 2) 
= [[10 20]
 [20 40]
 [30 60]
 [40 80]] 

np.dot(x, y) 
= np.dot((2, 2), (2,)) = z(2,) 
= [ 50 110] 

np.matmul(x, y) 
= np.matmul((2, 2), (2,)) = z(2,) 
= [ 50 110] 



In [121]:
algebra(
    [
        [1, 2],
        [3, 4]
    ],
    [
        [10, 20],
        [10, 20]
    ]
)

x(2, 2) = [[1 2]
 [3 4]] 

y(2, 2) = [[10 20]
 [10 20]] 

np.inner(x, y) 
= np.inner((2, 2), (2, 2)) = z(2, 2) 
= [[ 50  50]
 [110 110]] 

np.outer(x, y) 
= np.outer((2, 2), (2, 2)) = z(4, 4) 
= [[10 20 10 20]
 [20 40 20 40]
 [30 60 30 60]
 [40 80 40 80]] 

np.dot(x, y) 
= np.dot((2, 2), (2, 2)) = z(2, 2) 
= [[ 30  60]
 [ 70 140]] 

np.matmul(x, y) 
= np.matmul((2, 2), (2, 2)) = z(2, 2) 
= [[ 30  60]
 [ 70 140]] 



In [122]:
algebra(
    [
        [
            [1, 2],
            [3, 4],
            [5, 6],
        ],
        [
            [10, 20],
            [30, 40],
            [50, 60],
        ]
    ],
    [
        [
            [10, 20],
            [30, 40]
        ],
        [
            [50, 60],
            [70, 80]
        ],
        [
            [50, 60],
            [70, 80]
        ]
    ],
    mat=True
)

x(2, 3, 2) = [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[10 20]
  [30 40]
  [50 60]]] 

y(3, 2, 2) = [[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]

 [[50 60]
  [70 80]]] 

np.dot(x, y) 
= np.dot((2, 3, 2), (3, 2, 2)) = z(2, 3, 3, 2) 
= [[[[  70  100]
   [ 190  220]
   [ 190  220]]

  [[ 150  220]
   [ 430  500]
   [ 430  500]]

  [[ 230  340]
   [ 670  780]
   [ 670  780]]]


 [[[ 700 1000]
   [1900 2200]
   [1900 2200]]

  [[1500 2200]
   [4300 5000]
   [4300 5000]]

  [[2300 3400]
   [6700 7800]
   [6700 7800]]]] 

Error np.matmul(x, y) : operands could not be broadcast together with remapped shapes [original->remapped]: (2,3,2)->(2,newaxis,newaxis) (3,2,2)->(3,newaxis,newaxis)  and requested shape (3,2) 



In [123]:
algebra(
    [
        [
            [1, 2],
            [3, 4],
            [5, 6],
        ],
        [
            [10, 20],
            [30, 40],
            [50, 60],
        ],
        [
            [100, 200],
            [300, 400],
            [500, 600],
        ]
    ],
    [
        [
            [10, 20, 90],
            [30, 40, 90]
        ],
        [
            [50, 60, 90],
            [70, 80, 90]
        ],
        [
            [50, 60, 90],
            [70, 80, 90]
        ]
    ],
    mat=True
)

x(3, 3, 2) = [[[  1   2]
  [  3   4]
  [  5   6]]

 [[ 10  20]
  [ 30  40]
  [ 50  60]]

 [[100 200]
  [300 400]
  [500 600]]] 

y(3, 2, 3) = [[[10 20 90]
  [30 40 90]]

 [[50 60 90]
  [70 80 90]]

 [[50 60 90]
  [70 80 90]]] 

np.dot(x, y) 
= np.dot((3, 3, 2), (3, 2, 3)) = z(3, 3, 3, 3) 
= [[[[   70   100   270]
   [  190   220   270]
   [  190   220   270]]

  [[  150   220   630]
   [  430   500   630]
   [  430   500   630]]

  [[  230   340   990]
   [  670   780   990]
   [  670   780   990]]]


 [[[  700  1000  2700]
   [ 1900  2200  2700]
   [ 1900  2200  2700]]

  [[ 1500  2200  6300]
   [ 4300  5000  6300]
   [ 4300  5000  6300]]

  [[ 2300  3400  9900]
   [ 6700  7800  9900]
   [ 6700  7800  9900]]]


 [[[ 7000 10000 27000]
   [19000 22000 27000]
   [19000 22000 27000]]

  [[15000 22000 63000]
   [43000 50000 63000]
   [43000 50000 63000]]

  [[23000 34000 99000]
   [67000 78000 99000]
   [67000 78000 99000]]]] 

np.matmul(x, y) 
= np.matmul((3, 3, 2), (3, 2, 3)) = z(3, 3, 3

In [124]:
algebra(
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 0, 1, 2],
    ],
    [10, 20, 30, 40],
    mat=True
)

x(3, 4) = [[1 2 3 4]
 [5 6 7 8]
 [9 0 1 2]] 

y(4,) = [10 20 30 40] 

np.dot(x, y) 
= np.dot((3, 4), (4,)) = z(3,) 
= [300 700 200] 

np.matmul(x, y) 
= np.matmul((3, 4), (4,)) = z(3,) 
= [300 700 200] 

