In [28]:
import torch

x = torch.Tensor([
    1, 2, 3, 4, 5
])

z1 = x / x.sum()
print(x, z1, z1.sum())
z2 = x.exp() / x.exp().sum()
print(x, z2, z2.sum())

tensor([1., 2., 3., 4., 5.]) tensor([0.0667, 0.1333, 0.2000, 0.2667, 0.3333]) tensor(1.)
tensor([1., 2., 3., 4., 5.]) tensor([0.0117, 0.0317, 0.0861, 0.2341, 0.6364]) tensor(1.)


In [22]:
def softmax(x):
    print(x)
    e = x.exp()
    print(x, e)
    #return x.exp() / x.exp().sum()
    return x / x.sum()

In [23]:
z = softmax(x)
print(z)
print(z.sum())

tensor([1., 2., 3.])
tensor([1., 2., 3.]) tensor([ 2.7183,  7.3891, 20.0855])
tensor([0.1667, 0.3333, 0.5000])
tensor(1.)
