In [1]:
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device} device")

Using cpu device


In [3]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28 * 28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

In [4]:
model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [6]:
X = torch.rand(1, 28, 28, device=device)

logits = model(X)
print(logits)

pred_probab = nn.Softmax(dim=1)(logits)
print(pred_probab)

y_pred = pred_probab.argmax(1)
print(f"Predicted class: {y_pred}")

tensor([[-0.0710, -0.0415,  0.0955,  0.1015, -0.0927,  0.1347, -0.0242, -0.0669,
          0.0664,  0.0570]], grad_fn=<AddmmBackward0>)
tensor([[0.0914, 0.0941, 0.1079, 0.1086, 0.0894, 0.1123, 0.0958, 0.0918, 0.1049,
         0.1039]], grad_fn=<SoftmaxBackward0>)
Predicted class: tensor([5])


## Step by Step

In [15]:
input_image = torch.rand(3, 28, 28)
print(input_image.size())
# print(input_image)

flatten = nn.Flatten()
flat_image = flatten(input_image)
print(flat_image.size())
print(flat_image)

torch.Size([3, 28, 28])
torch.Size([3, 784])
tensor([[0.8924, 0.8669, 0.4707,  ..., 0.0467, 0.4612, 0.3922],
        [0.7088, 0.7593, 0.6354,  ..., 0.2427, 0.6627, 0.9795],
        [0.0723, 0.7445, 0.9378,  ..., 0.2145, 0.8267, 0.9196]])


In [16]:
layer1 = nn.Linear(in_features=28 * 28, out_features=20)
hidden1 = layer1(flat_image)
print(hidden1.size())
print(hidden1)

torch.Size([3, 20])
tensor([[-0.0658, -0.0139, -0.3080, -0.5287,  0.0061, -0.1981, -0.1983,  0.1943,
         -0.0097,  0.4913, -0.0382, -0.2668,  0.2088,  0.1824, -0.2438, -0.2093,
          0.2212,  0.1820, -0.1888,  0.2408],
        [ 0.1520,  0.0893, -0.7918, -0.5235, -0.0392,  0.1202, -0.1207, -0.0493,
          0.3067,  0.0863,  0.1504,  0.1479,  0.2374,  0.1710,  0.0589, -0.1587,
          0.1533,  0.4128, -0.1541,  0.2728],
        [-0.1673,  0.1132, -0.4955, -0.3664, -0.0685,  0.1800, -0.1417,  0.0095,
          0.1501,  0.1578, -0.0991,  0.2830,  0.4412,  0.4741,  0.0699, -0.2797,
          0.4160,  0.4302, -0.1801,  0.4973]], grad_fn=<AddmmBackward0>)


In [17]:
print(f"Before ReLU: {hidden1}\n\n")
hidden1 = nn.ReLU()(hidden1)
print(f"After ReLU: {hidden1}")

Before ReLU: tensor([[-0.0658, -0.0139, -0.3080, -0.5287,  0.0061, -0.1981, -0.1983,  0.1943,
         -0.0097,  0.4913, -0.0382, -0.2668,  0.2088,  0.1824, -0.2438, -0.2093,
          0.2212,  0.1820, -0.1888,  0.2408],
        [ 0.1520,  0.0893, -0.7918, -0.5235, -0.0392,  0.1202, -0.1207, -0.0493,
          0.3067,  0.0863,  0.1504,  0.1479,  0.2374,  0.1710,  0.0589, -0.1587,
          0.1533,  0.4128, -0.1541,  0.2728],
        [-0.1673,  0.1132, -0.4955, -0.3664, -0.0685,  0.1800, -0.1417,  0.0095,
          0.1501,  0.1578, -0.0991,  0.2830,  0.4412,  0.4741,  0.0699, -0.2797,
          0.4160,  0.4302, -0.1801,  0.4973]], grad_fn=<AddmmBackward0>)


After ReLU: tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0061, 0.0000, 0.0000, 0.1943, 0.0000,
         0.4913, 0.0000, 0.0000, 0.2088, 0.1824, 0.0000, 0.0000, 0.2212, 0.1820,
         0.0000, 0.2408],
        [0.1520, 0.0893, 0.0000, 0.0000, 0.0000, 0.1202, 0.0000, 0.0000, 0.3067,
         0.0863, 0.1504, 0.1479, 0.2374, 0.1710, 0.05

In [18]:
print(f"Model structure: {model}\n\n")

for name, param in model.named_parameters():
    print(f"Layer: {name} | Size: {param.size()} | Values : {param[:2]} \n")

Model structure: NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


Layer: linear_relu_stack.0.weight | Size: torch.Size([512, 784]) | Values : tensor([[-0.0040, -0.0021, -0.0344,  ...,  0.0191, -0.0070,  0.0337],
        [ 0.0258, -0.0100, -0.0063,  ..., -0.0259,  0.0250,  0.0012]],
       grad_fn=<SliceBackward0>) 

Layer: linear_relu_stack.0.bias | Size: torch.Size([512]) | Values : tensor([-0.0249,  0.0334], grad_fn=<SliceBackward0>) 

Layer: linear_relu_stack.2.weight | Size: torch.Size([512, 512]) | Values : tensor([[ 0.0425,  0.0401,  0.0320,  ..., -0.0180, -0.0419,  0.0132],
        [-0.0194, -0.0136,  0.0431,  ...,  0.0151,  0.0218, -0.0384]],
       grad_fn=<SliceBackward0>) 

Layer: linear_relu_stack.2.bias | 