In [1]:
import torch

In [8]:
x = torch.ones(5)  # input tensor
y = torch.zeros(3)  # expected output
w = torch.randn(5, 3, requires_grad=True)  # dim = input * output
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w) + b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)
print(x)
print(w)
print(b)
print(z)

tensor([1., 1., 1., 1., 1.])
tensor([[ 0.7415, -0.5737,  1.1724],
        [-0.8779, -0.4605,  0.2915],
        [-1.0195,  0.8573, -0.3787],
        [-0.3654,  1.3667,  0.7911],
        [ 0.8179,  1.4503,  0.8547]], requires_grad=True)
tensor([-0.5416,  0.5606, -0.2364], requires_grad=True)
tensor([-1.2451,  3.2007,  2.4945], grad_fn=<AddBackward0>)


In [3]:
print(f"Gradient function for z = {z.grad_fn}")
print(f"Gradient function for loss = {loss.grad_fn}")

Gradient function for z = <AddBackward0 object at 0x13965d580>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x13965d4f0>


In [4]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.0025, 0.0784, 0.0126],
        [0.0025, 0.0784, 0.0126],
        [0.0025, 0.0784, 0.0126],
        [0.0025, 0.0784, 0.0126],
        [0.0025, 0.0784, 0.0126]])
tensor([0.0025, 0.0784, 0.0126])


In [10]:
inp = torch.eye(5, requires_grad=True)
print(inp)
out = (inp + 1).pow(2)
print(out)
out.backward(torch.ones_like(inp), retain_graph=True)
print(f"First call\n{inp.grad}")
out.backward(torch.ones_like(inp), retain_graph=True)
print(f"\nSecond call\n{inp.grad}")
inp.grad.zero_()
out.backward(torch.ones_like(inp), retain_graph=True)
print(f"\nCall after zeroing gradients\n{inp.grad}")

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]], requires_grad=True)
tensor([[4., 1., 1., 1., 1.],
        [1., 4., 1., 1., 1.],
        [1., 1., 4., 1., 1.],
        [1., 1., 1., 4., 1.],
        [1., 1., 1., 1., 4.]], grad_fn=<PowBackward0>)
First call
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.],
        [2., 2., 2., 2., 4.]])

Second call
tensor([[8., 4., 4., 4., 4.],
        [4., 8., 4., 4., 4.],
        [4., 4., 8., 4., 4.],
        [4., 4., 4., 8., 4.],
        [4., 4., 4., 4., 8.]])

Call after zeroing gradients
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.],
        [2., 2., 2., 2., 4.]])
